///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace R_jenkins
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the R_jenkinsRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("3bb97a62-42ba-4d56-bd6a-eae76335a989")]
    public partial class R_jenkinsRepository : RepoGenBaseFolder
    {
        static R_jenkinsRepository instance = new R_jenkinsRepository();
        R_jenkinsRepositoryFolders.RxMainFrameAppFolder _rxmainframe;
        R_jenkinsRepositoryFolders.ChangeTheWelcomeMessageAppFolder _changethewelcomemessage;

        /// <summary>
        /// Gets the singleton class instance representing the R_jenkinsRepository element repository.
        /// </summary>
        [RepositoryFolder("3bb97a62-42ba-4d56-bd6a-eae76335a989")]
        public static R_jenkinsRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public R_jenkinsRepository() 
            : base("R_jenkinsRepository", "/", null, 0, false, "3bb97a62-42ba-4d56-bd6a-eae76335a989", ".\\RepositoryImages\\R_jenkinsRepository3bb97a62.rximgres")
        {
            _rxmainframe = new R_jenkinsRepositoryFolders.RxMainFrameAppFolder(this);
            _changethewelcomemessage = new R_jenkinsRepositoryFolders.ChangeTheWelcomeMessageAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("3bb97a62-42ba-4d56-bd6a-eae76335a989")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The RxMainFrame folder.
        /// </summary>
        [RepositoryFolder("49df676b-68db-4ef2-9aff-9adb660ba88a")]
        public virtual R_jenkinsRepositoryFolders.RxMainFrameAppFolder RxMainFrame
        {
            get { return _rxmainframe; }
        }

        /// <summary>
        /// The ChangeTheWelcomeMessage folder.
        /// </summary>
        [RepositoryFolder("8eea98ba-4f2f-40bf-a5fb-3c9a123c024a")]
        public virtual R_jenkinsRepositoryFolders.ChangeTheWelcomeMessageAppFolder ChangeTheWelcomeMessage
        {
            get { return _changethewelcomemessage; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class R_jenkinsRepositoryFolders
    {
        /// <summary>
        /// The RxMainFrameAppFolder folder.
        /// </summary>
        [RepositoryFolder("49df676b-68db-4ef2-9aff-9adb660ba88a")]
        public partial class RxMainFrameAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _enteryournameInfo;
            RepoItemInfo _btnsubmitusernameInfo;

            /// <summary>
            /// Creates a new RxMainFrame  folder.
            /// </summary>
            public RxMainFrameAppFolder(RepoGenBaseFolder parentFolder) :
                    base("RxMainFrame", "/form[@automationid='RxMainFrame']", parentFolder, 30000, null, true, "49df676b-68db-4ef2-9aff-9adb660ba88a", "")
            {
                _enteryournameInfo = new RepoItemInfo(this, "EnterYourName", "?/?/tabpage[@automationid='RxTabIntroduction']/?/?/text[@accessiblename='Enter your name']", ".//text[@accessiblename='Enter your name']", 30000, null, "22f154b9-d929-4f94-9908-d2693c7f5eae");
                _btnsubmitusernameInfo = new RepoItemInfo(this, "BtnSubmitUserName", "?/?/tabpage[@automationid='RxTabIntroduction']/button[@text='Submit']", ".//button[@text='Submit']", 30000, null, "fd7fa93a-cf1e-4ea4-a420-6fc8c19eab0a");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("49df676b-68db-4ef2-9aff-9adb660ba88a")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("49df676b-68db-4ef2-9aff-9adb660ba88a")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The EnterYourName item.
            /// </summary>
            [RepositoryItem("22f154b9-d929-4f94-9908-d2693c7f5eae")]
            public virtual Ranorex.Text EnterYourName
            {
                get
                {
                    return _enteryournameInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The EnterYourName item info.
            /// </summary>
            [RepositoryItemInfo("22f154b9-d929-4f94-9908-d2693c7f5eae")]
            public virtual RepoItemInfo EnterYourNameInfo
            {
                get
                {
                    return _enteryournameInfo;
                }
            }

            /// <summary>
            /// The BtnSubmitUserName item.
            /// </summary>
            [RepositoryItem("fd7fa93a-cf1e-4ea4-a420-6fc8c19eab0a")]
            public virtual Ranorex.Button BtnSubmitUserName
            {
                get
                {
                    return _btnsubmitusernameInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The BtnSubmitUserName item info.
            /// </summary>
            [RepositoryItemInfo("fd7fa93a-cf1e-4ea4-a420-6fc8c19eab0a")]
            public virtual RepoItemInfo BtnSubmitUserNameInfo
            {
                get
                {
                    return _btnsubmitusernameInfo;
                }
            }
        }

        /// <summary>
        /// The ChangeTheWelcomeMessageAppFolder folder.
        /// </summary>
        [RepositoryFolder("8eea98ba-4f2f-40bf-a5fb-3c9a123c024a")]
        public partial class ChangeTheWelcomeMessageAppFolder : RepoGenBaseFolder
        {

            /// <summary>
            /// Creates a new ChangeTheWelcomeMessage  folder.
            /// </summary>
            public ChangeTheWelcomeMessageAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ChangeTheWelcomeMessage", "/tooltip", parentFolder, 30000, null, true, "8eea98ba-4f2f-40bf-a5fb-3c9a123c024a", "")
            {
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("8eea98ba-4f2f-40bf-a5fb-3c9a123c024a")]
            public virtual Ranorex.ToolTip Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.ToolTip>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("8eea98ba-4f2f-40bf-a5fb-3c9a123c024a")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
